import type { Color } from 'chess.js'

export type OpeningStep = { san: string; comment: string }
export type OpeningCourse = {
  id: string
  name: string
  eco: string
  category: string
  summary: string
  studentSide: Color
  steps: OpeningStep[]
}

export const OPENING_CATEGORIES = [
  'Aberturas Abertas (1.e4 e5)',
  'Defesas Semiabertas (1.e4)',
  'Aberturas Fechadas (1.d4)',
  'Defesas Indianas',
  'Aberturas de Flanco',
] as const

export const OPENING_COURSES: OpeningCourse[] = [
  {
    id: 'italiana',
    name: 'Abertura Italiana (Giuoco Piano)',
    eco: 'C53',
    category: 'Aberturas Abertas (1.e4 e5)',
    summary: 'Desenvolvimento rápido mirando o ponto fraco f7, com luta clássica pelo centro.',
    studentSide: 'w',
    steps: [
      { san: 'e4', comment: 'Ocupa o centro e libera a dama e o bispo de casas claras.' },
      { san: 'e5', comment: 'As pretas respondem no centro em simetria, disputando d4 e f4.' },
      { san: 'Nf3', comment: 'Desenvolve atacando e5 e prepara um desenvolvimento rápido.' },
      { san: 'Nc6', comment: 'Defende o peão e desenvolve com tempo.' },
      { san: 'Bc4', comment: 'O bispo mira f7, o ponto mais fraco do campo preto no início.' },
      { san: 'Bc5', comment: 'Simetria: as pretas miram f2 e disputam o centro.' },
      { san: 'c3', comment: 'Prepara d4 para tomar o centro com apoio, típico da Giuoco Piano.' },
      { san: 'Nf6', comment: 'Desenvolve atacando e4 e continua o desenvolvimento natural.' },
      { san: 'd4', comment: 'Golpe central: se as pretas capturarem, as brancas recapturam com centro forte.' },
      { san: 'exd4', comment: 'Captura obrigatória para não ficar com espaço reduzido.' },
      { san: 'cxd4', comment: 'Recaptura mantendo um centro de peões amplo e espaço para as peças.' },
      { san: 'Bb4+', comment: 'Xeque intermediário que ganha tempo antes de decidir a casa do bispo.' },
    ],
  },
  {
    id: 'ruy-lopez',
    name: 'Ruy López (Espanhola)',
    eco: 'C60',
    category: 'Aberturas Abertas (1.e4 e5)',
    summary: 'Uma das aberturas mais estudadas da história, pressiona o cavalo que defende e5.',
    studentSide: 'w',
    steps: [
      { san: 'e4', comment: 'Controle central clássico.' },
      { san: 'e5', comment: 'Resposta simétrica no centro.' },
      { san: 'Nf3', comment: 'Ataca e5 e desenvolve.' },
      { san: 'Nc6', comment: 'Defende o peão central.' },
      { san: 'Bb5', comment: 'A ideia da Espanhola: pressiona indiretamente e5, pois o cavalo que o defende está preso pela ameaça a e5 via troca do Bb5.' },
      { san: 'a6', comment: 'A "variante Morphy": pergunta ao bispo, ganhando tempo se ele recuar ou trocar.' },
      { san: 'Ba4', comment: 'Mantém a pressão na diagonal, mirando eventualmente Nc6 outra vez.' },
      { san: 'Nf6', comment: 'Contra-ataca e4 e desenvolve com tempo.' },
      { san: 'O-O', comment: 'Coloca o rei em segurança antes de decidir o plano central.' },
      { san: 'Be7', comment: 'Desenvolvimento sólido, preparando o roque das pretas.' },
    ],
  },
  {
    id: 'siciliana-najdorf',
    name: 'Defesa Siciliana: Najdorf',
    eco: 'B90',
    category: 'Defesas Semiabertas (1.e4)',
    summary: 'A variante mais respeitada da Siciliana: as pretas preparam ...e5 ou ...b5 com flexibilidade.',
    studentSide: 'b',
    steps: [
      { san: 'e4', comment: 'As brancas ocupam o centro.' },
      { san: 'c5', comment: 'A Siciliana: as pretas lutam pelo centro de forma assimétrica, buscando contra-jogo no flanco da dama.' },
      { san: 'Nf3', comment: 'Desenvolve preparando d4.' },
      { san: 'd6', comment: 'Prepara ...Nf6 sem permitir e5 com tempo e abre diagonal para o bispo de casas claras.' },
      { san: 'd4', comment: 'Golpe central típico das aberturas semiabertas.' },
      { san: 'cxd4', comment: 'Captura obrigatória, abrindo a coluna c para as pretas.' },
      { san: 'Nxd4', comment: 'Recaptura centralizando o cavalo.' },
      { san: 'Nf6', comment: 'Ataca e4 e desenvolve.' },
      { san: 'Nc3', comment: 'Defende e4 e desenvolve.' },
      { san: 'a6', comment: 'O lance que dá nome à variante: impede Bb5/Nb5 e prepara ...e5 ou ...b5 com flexibilidade máxima.' },
    ],
  },
  {
    id: 'siciliana-dragao',
    name: 'Defesa Siciliana: Dragão',
    eco: 'B70',
    category: 'Defesas Semiabertas (1.e4)',
    summary: 'As pretas fianchetam o bispo em g7 mirando a grande diagonal contra o roque branco.',
    studentSide: 'b',
    steps: [
      { san: 'e4', comment: 'Controle central.' },
      { san: 'c5', comment: 'Siciliana: contra-jogo assimétrico.' },
      { san: 'Nf3', comment: 'Prepara d4.' },
      { san: 'd6', comment: 'Sustenta a expansão futura e libera o bispo de casas claras.' },
      { san: 'd4', comment: 'Golpe central.' },
      { san: 'cxd4', comment: 'Abre a coluna c.' },
      { san: 'Nxd4', comment: 'Cavalo centralizado.' },
      { san: 'Nf6', comment: 'Pressiona e4.' },
      { san: 'Nc3', comment: 'Defende e4.' },
      { san: 'g6', comment: 'Prepara o fianchetto: o bispo em g7 vai apontar para a diagonal a1-h8, geralmente contra um roque curto branco.' },
    ],
  },
  {
    id: 'francesa',
    name: 'Defesa Francesa',
    eco: 'C00',
    category: 'Defesas Semiabertas (1.e4)',
    summary: 'Estrutura sólida com peões travados; as pretas contra-atacam o centro com ...c5 ou ...f6.',
    studentSide: 'b',
    steps: [
      { san: 'e4', comment: 'Controle central.' },
      { san: 'e6', comment: 'Prepara ...d5 sustentando o golpe central sem expor o bispo de casas claras ainda.' },
      { san: 'd4', comment: 'As brancas ampliam o centro.' },
      { san: 'd5', comment: 'As pretas desafiam o centro imediatamente.' },
      { san: 'Nc3', comment: 'Defende e4 e desenvolve.' },
      { san: 'Nf6', comment: 'Pressiona e4 novamente, forçando uma decisão central.' },
      { san: 'Bg5', comment: 'Fixa o cavalo em f6 e prepara pressão na coluna e após e4-e5.' },
      { san: 'Be7', comment: 'Quebra o pino e prepara o roque.' },
    ],
  },
  {
    id: 'caro-kann',
    name: 'Defesa Caro-Kann',
    eco: 'B12',
    category: 'Defesas Semiabertas (1.e4)',
    summary: 'Similar à Francesa, mas sem trancar o bispo de casas claras: uma das defesas mais sólidas contra 1.e4.',
    studentSide: 'b',
    steps: [
      { san: 'e4', comment: 'Controle central.' },
      { san: 'c6', comment: 'Prepara ...d5 mantendo a diagonal do bispo de casas claras livre para desenvolvê-lo antes de ...e6.' },
      { san: 'd4', comment: 'Amplia o centro.' },
      { san: 'd5', comment: 'Desafia o centro branco.' },
      { san: 'Nc3', comment: 'Defende e4.' },
      { san: 'dxe4', comment: 'As pretas resolvem a tensão central capturando.' },
      { san: 'Nxe4', comment: 'Recaptura natural, centralizando o cavalo.' },
      { san: 'Bf5', comment: 'Desenvolve o bispo problemático antes de jogar ...e6, a grande vantagem estrutural da Caro-Kann sobre a Francesa.' },
    ],
  },
  {
    id: 'escandinava',
    name: 'Defesa Escandinava',
    eco: 'B01',
    category: 'Defesas Semiabertas (1.e4)',
    summary: 'As pretas trocam o peão central imediatamente e trazem a dama cedo ao jogo.',
    studentSide: 'b',
    steps: [
      { san: 'e4', comment: 'Controle central.' },
      { san: 'd5', comment: 'Desafia e4 imediatamente, aceitando trocar peças no centro.' },
      { san: 'exd5', comment: 'As brancas capturam, ganhando um tempo de desenvolvimento.' },
      { san: 'Qxd5', comment: 'Recaptura com a dama; ela ficará exposta a um tempo de ataque, mas as pretas obtêm um jogo simples.' },
      { san: 'Nc3', comment: 'Desenvolve atacando a dama e ganhando tempo.' },
      { san: 'Qa5', comment: 'Recuo mais popular: mantém pressão em e5/c3 e prepara ...Nf6, ...c6, ...Bf5.' },
    ],
  },
  {
    id: 'pirc',
    name: 'Defesa Pirc',
    eco: 'B07',
    category: 'Defesas Semiabertas (1.e4)',
    summary: 'As pretas cedem o centro de propósito para golpeá-lo depois com peças e peões flanco.',
    studentSide: 'b',
    steps: [
      { san: 'e4', comment: 'Controle central.' },
      { san: 'd6', comment: 'Lance flexível que adia a definição da estrutura central.' },
      { san: 'd4', comment: 'Amplia o centro sem oposição imediata.' },
      { san: 'Nf6', comment: 'Ataca e4 e desenvolve.' },
      { san: 'Nc3', comment: 'Defende e4.' },
      { san: 'g6', comment: 'Prepara o fianchetto do bispo em g7, a peça-chave do plano hipermoderno das pretas.' },
    ],
  },
  {
    id: 'gambito-dama-recusado',
    name: 'Gambito da Dama Recusado',
    eco: 'D30',
    category: 'Aberturas Fechadas (1.d4)',
    summary: 'As pretas recusam o "gambito" (que na verdade não perde peão) e sustentam o centro com ...e6.',
    studentSide: 'w',
    steps: [
      { san: 'd4', comment: 'Controle central pelo lado da dama.' },
      { san: 'd5', comment: 'Resposta simétrica clássica.' },
      { san: 'c4', comment: 'O "gambito": oferece o peão c para desviar a atenção do centro, mas se capturado as brancas o recuperam com facilidade.' },
      { san: 'e6', comment: 'As pretas recusam a captura e reforçam d5 solidamente, abrindo a diagonal do bispo de casas claras... por enquanto trancada.' },
      { san: 'Nc3', comment: 'Desenvolve e mantém a pressão central.' },
      { san: 'Nf6', comment: 'Desenvolvimento natural, pressionando d5 e e4.' },
    ],
  },
  {
    id: 'eslava',
    name: 'Defesa Eslava',
    eco: 'D10',
    category: 'Aberturas Fechadas (1.d4)',
    summary: 'Sustenta d5 sem trancar o bispo de casas claras, diferente do GDR.',
    studentSide: 'b',
    steps: [
      { san: 'd4', comment: 'Controle central.' },
      { san: 'd5', comment: 'Resposta simétrica.' },
      { san: 'c4', comment: 'Desafia o centro preto.' },
      { san: 'c6', comment: 'Defende d5 mantendo livre a diagonal para o bispo de casas claras, que poderá sair antes de ...e6.' },
      { san: 'Nf3', comment: 'Desenvolvimento flexível.' },
      { san: 'Nf6', comment: 'Desenvolvimento simétrico, mantendo a tensão central.' },
    ],
  },
  {
    id: 'londres',
    name: 'Sistema Londres',
    eco: 'D02',
    category: 'Aberturas Fechadas (1.d4)',
    summary: 'Sistema de desenvolvimento fácil de aprender: o bispo sai antes de e3, quase independente do que as pretas jogam.',
    studentSide: 'w',
    steps: [
      { san: 'd4', comment: 'Controle central.' },
      { san: 'd5', comment: 'Resposta natural das pretas.' },
      { san: 'Nf3', comment: 'Desenvolve com flexibilidade.' },
      { san: 'Nf6', comment: 'Desenvolvimento simétrico.' },
      { san: 'Bf4', comment: 'A marca do Sistema Londres: o bispo sai antes do peão e3 travá-lo, mirando a diagonal b8-h2.' },
      { san: 'e6', comment: 'As pretas preparam o desenvolvimento do bispo de casas claras e o roque.' },
      { san: 'e3', comment: 'Agora sim as brancas fecham a diagonal, com a estrutura já montada e um plano fácil de repetir em qualquer partida.' },
    ],
  },
  {
    id: 'nimzo-india',
    name: 'Defesa Nimzo-Índia',
    eco: 'E20',
    category: 'Defesas Indianas',
    summary: 'As pretas pinam o cavalo em c3 para controlar e4 sem depender de peões.',
    studentSide: 'b',
    steps: [
      { san: 'd4', comment: 'Controle central.' },
      { san: 'Nf6', comment: 'Desenvolvimento hipermoderno: controla e4 com uma peça, não com um peão.' },
      { san: 'c4', comment: 'Amplia o espaço central.' },
      { san: 'e6', comment: 'Prepara ...Bb4, a ideia central da defesa.' },
      { san: 'Nc3', comment: 'Desenvolve, mas expõe o cavalo a um pino.' },
      { san: 'Bb4', comment: 'O lance que dá nome à abertura: pina o cavalo, pressionando o controle de e4 e ameaçando dobrar peões brancos.' },
    ],
  },
  {
    id: 'india-do-rei',
    name: 'Defesa Índia do Rei',
    eco: 'E60',
    category: 'Defesas Indianas',
    summary: 'As pretas cedem o centro para atacá-lo depois com ...e5 ou ...c5 e lançar um ataque no flanco do rei.',
    studentSide: 'b',
    steps: [
      { san: 'd4', comment: 'Controle central.' },
      { san: 'Nf6', comment: 'Controle hipermoderno de e4.' },
      { san: 'c4', comment: 'Amplia o espaço.' },
      { san: 'g6', comment: 'Prepara o fianchetto característico da Índia do Rei.' },
      { san: 'Nc3', comment: 'Desenvolve e prepara e4.' },
      { san: 'Bg7', comment: 'O bispo fianchetado controla a grande diagonal e apoiará o rompimento central ...e5 mais tarde.' },
    ],
  },
  {
    id: 'grunfeld',
    name: 'Defesa Grünfeld',
    eco: 'D80',
    category: 'Defesas Indianas',
    summary: 'As pretas permitem um grande centro branco para atacá-lo imediatamente com peças.',
    studentSide: 'b',
    steps: [
      { san: 'd4', comment: 'Controle central.' },
      { san: 'Nf6', comment: 'Controle hipermoderno de e4.' },
      { san: 'c4', comment: 'Amplia o espaço.' },
      { san: 'g6', comment: 'Prepara o fianchetto.' },
      { san: 'Nc3', comment: 'Desenvolve.' },
      { san: 'd5', comment: 'A ideia Grünfeld: desafia o centro imediatamente, aceitando ceder um grande centro branco de peões para atacá-lo depois com o bispo em g7 e peças ativas.' },
    ],
  },
  {
    id: 'inglesa',
    name: 'Abertura Inglesa',
    eco: 'A10',
    category: 'Aberturas de Flanco',
    summary: 'Abertura flexível pelo flanco da dama que pode transpor para estruturas fechadas ou de Índia do Rei com cores trocadas.',
    studentSide: 'w',
    steps: [
      { san: 'c4', comment: 'Controla d5 a distância sem comprometer o centro imediatamente, mantendo várias transposições possíveis.' },
      { san: 'e5', comment: 'As pretas respondem no centro, criando uma posição de Siciliana com cores trocadas.' },
      { san: 'Nc3', comment: 'Desenvolve controlando d5.' },
      { san: 'Nf6', comment: 'Desenvolvimento natural.' },
      { san: 'Nf3', comment: 'Continua o desenvolvimento antes de decidir a estrutura central.' },
    ],
  },
  {
    id: 'reti',
    name: 'Abertura Reti',
    eco: 'A04',
    category: 'Aberturas de Flanco',
    summary: 'Sistema hipermoderno onde as brancas controlam o centro a distância e decidem o plano depois de ver as pretas.',
    studentSide: 'w',
    steps: [
      { san: 'Nf3', comment: 'Controla e5/d4 com uma peça em vez de peões, mantendo total flexibilidade de plano.' },
      { san: 'd5', comment: 'As pretas ocupam o centro convencionalmente.' },
      { san: 'c4', comment: 'Desafia d5 a distância, podendo transpor para Inglesa ou Catalã dependendo da resposta.' },
      { san: 'e6', comment: 'As pretas sustentam o centro de forma sólida.' },
      { san: 'g3', comment: 'Prepara o fianchetto do bispo, uma continuação típica desse sistema.' },
    ],
  },
  {
    id: 'vienense',
    name: 'Abertura Vienense',
    eco: 'C25',
    category: 'Aberturas Abertas (1.e4 e5)',
    summary: 'Desenvolve o cavalo antes do Nf3, mantendo a opção de f4 mais tarde.',
    studentSide: 'w',
    steps: [
      { san: 'e4', comment: 'Controle central.' },
      { san: 'e5', comment: 'Resposta simétrica.' },
      { san: 'Nc3', comment: 'Desenvolve defendendo a possibilidade futura de f4 sem enfraquecer o rei imediatamente.' },
      { san: 'Nf6', comment: 'Desenvolvimento natural, pressionando e4.' },
      { san: 'f4', comment: 'Rompimento tático que busca abrir linhas rapidamente, no estilo dos gambitos do século XIX.' },
    ],
  },
  {
    id: 'gambito-rei',
    name: 'Gambito do Rei',
    eco: 'C30',
    category: 'Aberturas Abertas (1.e4 e5)',
    summary: 'Sacrifício de peão para abrir a coluna f e atacar rapidamente, uma das aberturas mais antigas e agressivas.',
    studentSide: 'w',
    steps: [
      { san: 'e4', comment: 'Controle central.' },
      { san: 'e5', comment: 'Resposta simétrica.' },
      { san: 'f4', comment: 'Oferece um peão para abrir a coluna f e ganhar tempo de desenvolvimento contra e5.' },
      { san: 'exf4', comment: 'As pretas aceitam o gambito, ficando com um peão a mais mas atrasadas no desenvolvimento.' },
      { san: 'Nf3', comment: 'Impede ...Qh4+ e prepara recuperar o peão com iniciativa.' },
    ],
  },
]

export function courseCategories() {
  const set = new Set(OPENING_COURSES.map((course) => course.category))
  return OPENING_CATEGORIES.filter((category) => set.has(category))
}
